### PR TITLE
util/packer: Pin kernel version to work around Docker/AUFS bug

### LINKED ISSUE #2365: Build hangs on 'controller: docker build controller'
The culprit seems to be the "/var/lib/dpkg/info/ca-certificates-java.postinst configure" process, which spawns a defunct Java process. https://github.com/docker/docker/issues/18180 seems to be the ultimate cause. Reproduces every time in our setup.

### PR DESCRIPTION
**Pull request by titanous**
Ubuntu kernel 3.19.0-39 is does not trigger this bug: https://github.com/docker/docker/issues/18180

Verified with:

    docker run -it --rm akihirosuda/test18180

Fixes #2365

### CODE REVIEW

**Comment by lmars** [comment]
LGTM

**Comment by josephglanville** [comment]
LGTM

**Comment by temujin9** [comment]
Is there a good place to watch for the results of the AMI build process folding this in? This blocks me working https://github.com/flynn/flynn/issues/1535 (at long, long last), so I'd like to keep an eye on it without bugging y'all.

**Comment by titanous** [comment]
I'm just about to run the build. You can watch https://dl.flynn.io/ec2/images.json but I'll also post a comment when it is up.

**Comment by titanous** [comment]
The new AMI is up.

**Pull request merged**
