### PR TITLE
host/cli: collect-debug-info only collect system app logs by default

### PR DESCRIPTION
**Pull request by josephglanville**
Right now this doesn't properly work when it has to fallback to on disk files.
Suggestions on what to do in that case?

### CODE REVIEW

**Comment by jvatic** [comment]
LGTM

**Comment by lmars** [comment]
> Right now this doesn't properly work when it has to fallback to on disk files.

We could put the system logs in `/var/log/flynn/system`

**Comment by josephglanville** [comment]
I'm thinking this is a good start. Redirecting system logs to a different directory turned out to be more complex than I had hoped and I don't think the benefit out-weighs that complexity.

Maybe we could prompt the user on fallback so they are aware that it's going to upload everything that is stored locally? (and have the chance to abort instead if they want)

**Comment by titanous** [comment]
Yeah, a prompt on fallback is fine.

**Comment by jvatic** [comment]
Note that the installer will need updating to handle the prompt

**Comment by josephglanville** [comment]
@jvatic I think it would be reasonable for the installer to pass flag to skip prompt as there should be no non-system apps at installation time? Unless the installer can trigger debug logs outside of initial install/bootstrap?

**Comment by jvatic** [comment]
@josephglanville Yeah, that's reasonable

**Pull request closed without merging**
