### PR TITLE
Add support for .profile

### LINKED ISSUE #3545: .profile support
Support `.profile` scripts in the root of apps.

> During startup, the container starts a bash shell that runs any code in $HOME/.profile before executing the dyno’s command. You can put bash code in this file to manipulate the initial environment, at runtime, for all dyno types in your app.
> The .profile script will be sourced after the app’s config vars.

https://devcenter.heroku.com/articles/dynos#the-profile-file

### PR DESCRIPTION
**Pull request by kylefritz**
fixes #3545

https://devcenter.heroku.com/articles/dynos#the-profile-file

### CODE REVIEW

**Comment by lmars** [comment]
@kylefritz please prefix your commit message with `slugrunner: ` and add a [DCO sign-off](https://github.com/flynn/flynn/blob/master/CONTRIBUTING.md#developers-certificate-of-origin).

**Comment by kylefritz** [comment]
@lmars i amended that commit.

**Comment by lmars** [comment]
@kylefritz the DCO sign-off is incorrect, you need to add a "Signed-off-by" line to the commit message (which you can do with `git commit --amend --signoff`), sorry if this wasn't clear.

**Comment by kylefritz** [comment]
@lmars i think i've got it right now. thanks for your help.

**Comment by kylefritz** [comment]
@lmars i think i have this commit corrected.

i'm seeing a failing ci build but i don't think my change is to blame.

**Comment by lmars** [comment]
Thanks!

**Pull request merged**
