### PR TITLE
Controller client versioning foundation

### PR DESCRIPTION
**Pull request by jvatic**
This moves `controller.Client` into an interface to allow using a different client depending on the server version being communicated with.

Refs #2759

### CODE REVIEW

**Comment by jvatic** [comment]
ping @titanous @lmars for review

**Comment by jvatic** [comment]
(commits need squashing)

**Comment by lmars** [comment]
LGTM

**Comment by titanous** [comment]
LGTM

**Comment by jvatic** [comment]
Squashed commits, merging...

**Pull request merged**
