### PR TITLE
status: Add CORS response headers

### PR DESCRIPTION
**Pull request by jvatic**

### CODE REVIEW

**Comment by josephglanville** [comment]
LGTM.

I assume this is to allow status endpoint to be accessed from Javascript on dashboard?

**Comment by titanous** [comment]
I don't think that map operation is safe. I have a commit you can cherrypick on the go1.6 branch.

**Comment by titanous** [comment]
LGTM

**Comment by jvatic** [comment]
@josephglanville Yup. @titanous I've replaced e72c00b with 05b8f92.

**Pull request merged**
