### PR TITLE
Cedarish updates

### PR DESCRIPTION
**Pull request by titanous**

### CODE REVIEW

**Comment by lmars** [comment]
We don't currently have a strategy, but we need to update the dependent images with a tag so that they use the updated cedarish image.

The easiest thing would be to build it locally and push it to Docker Hub with a tag like `flynn/cedarish:20160504` then use that as a reference.

**Comment by titanous** [comment]
In the past I've just cleared the Docker cache on the build machine, which should result in the right references, right?

**Comment by lmars** [comment]
@titanous I guess that works too, but I think using an explicit tag gives us a bit more confidence that it has been dealt with when reviewing a PR.

**Comment by lmars** [comment]
LGTM

**Comment by josephglanville** [comment]
LGTM

**Comment by lmars** [comment]
FYI I built the cedarish image manually on the build machine, tagged it as both `flynn/cedarish:latest` and `flynn/cedarish:20160510` and pushed to Docker Hub.

**Pull request merged**
