### PR TITLE
test: Fix SchedulerSuite.TestOmniJobs

### LINKED ISSUE #1855: ci: TestOmniJobs failing due to router blocking on startup
`TestOmniJobs` is consistently failing in CI when [adding a new host](https://github.com/flynn/flynn/blob/master/test/helper.go#L194-L229) because the router is blocking before it gets chance to register in discoverd.

I sent a SIGQUIT to the router and here is the result (from [this build](https://ci.flynn.io/builds/20150910211937-8611f399)):

https://gist.github.com/lmars/851a209412cc653f9044

The router is blocked starting the HTTP listener (specifically at [startSync](https://github.com/flynn/flynn/blob/master/router/http.go#L94)), and following the goroutines, [setting initial routes](https://github.com/flynn/flynn/blob/master/router/data_store.go#L223-L227) is blocked [creating a service cache](https://github.com/flynn/flynn/blob/master/router/http.go#L227) (specifically [waiting for a current event](https://github.com/flynn/flynn/blob/master/discoverd/cache/cache.go#L95)).

### PR DESCRIPTION
**Pull request by lmars**
Fixes #1855.

/cc @benbjohnson

### CODE REVIEW

**Comment by benbjohnson** [comment]
:+1:

**Comment by lmars** [comment]
@benbjohnson @titanous please review

**Comment by titanous** [comment]
LGTM

**Comment by benbjohnson** [comment]
lgtm

**Pull request merged**
