### PR TITLE
Fix gitreceive tar

### LINKED ISSUE #1799: error: RPC failed
Output from git push flynn master:
```text
Counting objects: 509, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (471/471), done.
Writing objects: 100% (509/509), 7.62 MiB | 1.14 MiB/s, done.
Total 509 (delta 187), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
No app release, specify a release with --release
```

Debug: https://gist.github.com/anonymous/109049e1f7e71c417183

Similar issue, different project: https://github.com/douban/gpack/pull/2

### PR DESCRIPTION
**Pull request by titanous**
Directories were not being saved in the repo cache tar file correctly, which caused git to not see a valid repository. Also, did a bit of refactoring to surface errors from the tar upload correctly.

Closes #1799

### CODE REVIEW

**Comment by titanous** [comment]
I'll add a test as soon as I can figure out how to reproduce a failing repo.

**Comment by lmars** [comment]
LGTM pending test

**Comment by titanous** [comment]
Test added.

**Comment by lmars** [comment]
LGTM++

**Pull request merged**
