### PR TITLE
scheduler: Simplify main loop select

### PR DESCRIPTION
**Pull request by lmars**
There doesn't seem to be a reason to prioritise certain channels, and this removes the need for a sleep in the loop, as it will block on all channels if there is nothing to do.

/cc @jzila

### CODE REVIEW

**Comment by lmars** [comment]
@jzila lots of failures in the latest build. If there is an explicit need to prioritise the channels, it may be worth making it clearer why in the comments. Happy to drop this change if the next build fails as badly.

**Comment by jzila** [comment]
@lmars yeah I was about to say. I'll add comments to explain why the priority is necessary.

**Comment by jzila** [comment]
Ultimately it comes down to this: if the scheduler decides to rectify or handle job requests before handling events from the hosts/cluster/controller, then it can cause behavior that thrashes (e.g. creating extra jobs, deleting extra jobs, etc).

**Comment by lmars** [comment]
Closing as this was fixed in #1843

**Pull request closed without merging**
