### PR TITLE
cli: Clarified remote usage, per issue #2404

### LINKED ISSUE #2404: "Usage" for `flynn release add` could be improved
Spent a bit of time with this sequence of operations:

```
$ flynn remote add sentry
no apps in git remotes
```

```
$ flynn remote -c default -a sentry add sentry
usage: flynn remote add [<remote>] [-y]
```

Got the tip in the IRC channel to do this:

```
 $ flynn -a sentry remote add sentry
Created remote sentry with url
```

It would make sense to just modify the 'usage' to include the 'a' option, so that I would know to try that.

### PR DESCRIPTION
**Pull request by ociule**
Clarified remote usage, closes #2404

### CODE REVIEW

**Comment by titanous** [comment]
Unfortunately it looks like this change breaks docopt parsing.

```text
++ 15:14:16.241 /home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn -a remote-94f2c076 remote add
usage: flynn [-a ] remote add [] [-y]

test_cli.go:1032:
    // create the default remote
    t.Assert(r.flynn("-a", remoteApp, "remote", "add"), Succeeds)
... result *main.CmdResult = &main.CmdResult{Cmd:[]string{"/home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn", "-a", "remote-94f2c076", "remote", "add"}, Output:"usage: flynn [-a ] remote add [] [-y]\n", Err:(*exec.ExitError)(0xc8203de960)}
```

**Comment by ociule** [comment]
I'm having trouble running just test_cli. I tried `vagrant@flynn:~/go/src/github.com/flynn/flynn$ script/run-integration-tests -f test/test_cli.go` but that just runs and reports `OK: 0 passed`

**Comment by titanous** [comment]
Run with `-f TestRemote`

**Comment by titanous** [comment]
Closing, this patch appears to be broken. Feel free to open a new PR with a working patch.

**Pull request closed without merging**
