### PR TITLE
worker: Don't rollback one-by-one deploy if cleanup fails

### PR DESCRIPTION
**Pull request by lmars**

### CODE REVIEW

**Comment by josephglanville** [comment]
So with this change the new formation will stay scaled up but the deployment will be marked as failed?

**Comment by lmars** [comment]
> So with this change the new formation will stay scaled up but the deployment will be marked as failed?

Correct, with the hope that the next time the deploy is attempted, it is marked as done.

I plan to rewrite deployments once #2744 is merged, so this is just a minor change to prevent the "failed" deployment nuking a controller release for no good reason.

**Comment by josephglanville** [comment]
Sounds good. LGTM

**Comment by titanous** [comment]
LGTM

**Pull request merged**
