### PR TITLE
Stopped jobs now get saved to the controller

### PR DESCRIPTION
**Pull request by jzila**
Added job state to represent jobs that are stopping but not yet stopped, to ensure they get saved to the controller

Signed-off-by: John Zila <john@jzila.com>

### CODE REVIEW

**Comment by lmars** [comment]
LGTM

**Comment by lmars** [comment]
@jzila the scheduler loop got blocked in the latest failure stopping a job, even though we now have the 5s host client timeout.

From the end of job `b60f8a0b-b57421e9-0e4a-4838-b51b-c0c44992ebce`:

```
t=2015-09-26T02:36:56+0000 lvl=info msg="requesting host to stop job" component=scheduler fn=stopJob req.host.id= req.job.id= job.type=printer
t=2015-09-26T02:37:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:37:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:37:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:38:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:38:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:38:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:39:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:39:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:39:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:40:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:40:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:40:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:41:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:41:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:41:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:42:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:42:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:42:51+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:43:21+0000 lvl=info msg="triggering job sync" component=scheduler
t=2015-09-26T02:43:21+0000 lvl=info msg="triggering formation sync" component=scheduler
t=2015-09-26T02:43:51+0000 lvl=info msg="triggering job sync" component=scheduler
```

**Comment by lmars** [comment]
@jzila let me know if you look at this today, I am looking into it and may make some changes.

**Comment by jzila** [comment]
@lmars found the request in the appropriate host log...it never returned:
```
t=2015-09-26T02:36:56+0000 lvl=info msg="request started" component=host req_id=a20aadb8-3e29-48c5-b3ff-1a9415f2562b method=DELETE path=/host/jobs/a17711e9-fff8406d-707e-484d-aa29-e9e0924ad53c client_ip=10.69.20.3
now=2015-09-26T02:36:56+0000 state=initial backend=libvirt-lxc fn=watch_container job.id=a17711e9-d1f46f3f-8489-45d5-b5d1-c23a16f11752 app=host at=change                                                            
now=2015-09-26T02:36:56+0000 at=wait_attach job.id=a17711e9-d1f46f3f-8489-45d5-b5d1-c23a16f11752 app=host backend=libvirt-lxc fn=watch_container                                                                     
now=2015-09-26T02:36:56+0000 app=host backend=libvirt-lxc fn=watch_container job.id=a17711e9-ed02bf26-2d2e-4f69-8898-1b57fee22ee9 at=resume                                                                          
now=2015-09-26T02:36:56+0000 app=host job.id=a17711e9-e3d47ced-4973-4285-98ae-a743a239a902 backend=libvirt-lxc fn=watch_container at=resume                                                                          
now=2015-09-26T02:36:56+0000 backend=libvirt-lxc fn=watch_container job.id=a17711e9-fb89fc2a-44e2-4d66-92a7-dfe337182337 at=resume app=host                                                                          
now=2015-09-26T02:36:56+0000 app=host backend=libvirt-lxc fn=watch_container job.id=a17711e9-d1f46f3f-8489-45d5-b5d1-c23a16f11752 at=resume                                                                          
now=2015-09-26T02:36:56+0000 fn=watch_container job.id=a17711e9-fb89fc2a-44e2-4d66-92a7-dfe337182337 state=failed at=change app=host backend=libvirt-lxc                                                             
now=2015-09-26T02:36:56+0000 at=change status=error err='exec: "this-is-gonna-fail": executable file not found in $PATH' job.id=a17711e9-fb89fc2a-44e2-4d66-92a7-dfe337182337 app=host backend=libvirt-lxc fn=watch_container                                                                                                                                                                                                             
now=2015-09-26T02:36:56+0000 app=host backend=libvirt-lxc fn=cleanup job.id=a17711e9-fb89fc2a-44e2-4d66-92a7-dfe337182337 at=start                                                                                   
now=2015-09-26T02:36:56+0000 backend=libvirt-lxc fn=unbind_mounts job.id=a17711e9-fb89fc2a-44e2-4d66-92a7-dfe337182337 at=start app=host                                                                             
now=2015-09-26T02:36:56+0000 job.id=a17711e9-e3d47ced-4973-4285-98ae-a743a239a902 backend=libvirt-lxc fn=watch_container at=change state=running app=host                                                            
now=2015-09-26T02:36:56+0000 app=host job.id=a17711e9-e3d47ced-4973-4285-98ae-a743a239a902 backend=libvirt-lxc fn=watch_container at=running                                                                         
now=2015-09-26T02:36:56+0000 at=change app=host backend=libvirt-lxc fn=watch_container job.id=a17711e9-d1f46f3f-8489-45d5-b5d1-c23a16f11752 state=running                                                            
```

**Pull request merged**
