### PR TITLE
Added documentation about MAVEN_CUSTOM_OPTS

### LINKED ISSUE #2700: Java application: How to specify maven properties for building?
Hi,
we build our wars with some parameters as configuration instead of using environment variables. This is legacy and can't easily be changed.

```bash
mvn  -DdatabaseUsername="asdasd" -DdatabaseUrl="jdbc:mysql://foo.bar:3306/blubb" \
-DdatabasePassword="asd123" clean war:war install
```

I already tried to set the environment variable JAVA_TOOL_OPTIONS upfront, but that didn't do the trick.

Is there a way to define them and adjust the Maven call?

### PR DESCRIPTION
**Pull request by philiplb**
on deploying Java applications

Closes #2700

Signed-off-by: Philip Lehmann-Boehm <philip@philiplb.de>

### CODE REVIEW

**Comment by jvatic** [comment]
The commit message should have a `docs: ` prefix.

**Comment by philiplb** [comment]
Prefixed the commit message with "docs: ".

**Comment by lmars** [comment]
LGTM

**Comment by lmars** [comment]
Thanks!

**Pull request merged**
