### PR TITLE
Adds encryption to EBS volumes

### PR DESCRIPTION
**Pull request by kenaniah**
Signed-off-by: Kenaniah <kenaniah@gmail.com>

### CODE REVIEW

**Comment by titanous** [comment]
Awesome, this looks good! Do you mind rewriting the commit message to have a `installer: ` prefix? Thanks!

**Comment by kenaniah** [comment]
@titanous no problem. Should be updated now.

**Comment by titanous** [comment]
Do you mind also rebasing on the latest master? The branch appears to be a bit behind. After that I'll merge, sorry for the trouble!

**Comment by kenaniah** [comment]
No worries. Just rebased.

**Pull request merged**
