### PR TITLE
bootstrap: Only migrate active slugs / Docker images

### PR DESCRIPTION
**Pull request by lmars**

### CODE REVIEW

**Comment by titanous** [comment]
Can we migrate the current app releases as well? That would allow scaling up apps that are scaled down at the time of the backup.

**Comment by lmars** [comment]
@titanous comments addressed

**Comment by lmars** [comment]
Oh in fact I need to update `host/cli/bootstrap.go`...

**Comment by lmars** [comment]
@titanous ok I updated the bootstrap code to just check if there are any legacy slugs / Docker images before running the relevant migrators.

**Pull request merged**
