### PR TITLE
Add Canada Central to AWSRegionPicker

### PR DESCRIPTION
**Pull request by beautifulcode**
Allows for new Canada region to be selected as an option via installer.
Need to confirm this region doesn't require any additional changes to the installer etc to fully function.

### CODE REVIEW

**Comment by lmars** [comment]
This needs to be added to the Packer template [here](https://github.com/flynn/flynn/blob/master/util/packer/ubuntu.json#L100-L109) so that an AMI is available in the region.

**Comment by lmars** [comment]
Please add a [DCO sign off](https://github.com/flynn/flynn/blob/master/CONTRIBUTING.md#developers-certificate-of-origin) to the commit message, and prefix the commit message with `installer: `.

**Comment by beautifulcode** [comment]
👍 will do.

**Comment by beautifulcode** [comment]
@lmars rebased to squash into single commit with `installer:` prefix and DCO sign off.

**Comment by lmars** [comment]
We are going to hold off merging this just yet as it will break the installer as there will be no AMI in the new region, so we need to create that AMI first (which we will do soon).

**Comment by beautifulcode** [comment]
Sure. Appreciate the insight and effort. Is that something that is quick to create/config? Assuming that is outside of this repo? Let me know if I can help. I'm looking forward to spinning up some some Canadian clusters eh? :) Thanks!

**Comment by lmars** [comment]
@beautifulcode we build the AMIs using [Packer](https://packer.io), and we usually only run it when we do a stable release once a month, but I'll merge this now and get the AMIs released sooner.

**Pull request merged**
