### PR TITLE
appliance/postgresql: Add PGRouting extension to PostgreSQL appliance

### PR DESCRIPTION
**Pull request by josephglanville**
This enables additional GIS workloads including importing and working with the Open Street Map dataset.

### CODE REVIEW

**Comment by josephglanville** [comment]
On the topic of extensions, as they are so hard to customise would it make sense to just install all the extensions available in the pgdg repo?

**Comment by titanous** [comment]
How many other extensions are there?

**Comment by josephglanville** [comment]
These are the ones built and packaged by pgdg:
debversion
ip4r
orafce
pgespresso
pgextwlist
pgfincore
pgmp
pgpool2
pgq3
pgrouting
plproxy
plr
plv8
postgis
prefix
preprepare
python-multicorn
python3-multicorn
reorg
repmgr
slony

Most of them are related to replication and backup tools so maybe not super useful but installing them is probably no harm. They may come in handy if you want to setup trigger based replication to/from an external database though. 

Then there is stuff like ip4r, which are IP address range types, and python-multicorn which is an extension for building foreign data wrappers.

I am not too fussed either way, just figured it would be useful because inevitably someone will want one of these things.

**Comment by titanous** [comment]
I'm going to merge this for now, let's see if more requests come up before moving forward with others.

**Pull request merged**
