### PR TITLE
router: Add support for HTTP/2

### LINKED ISSUE #1050: Implement HTTP/2
The router should support HTTP/2.

### PR DESCRIPTION
**Pull request by titanous**
Go 1.6 has great support for HTTP/2 so this is entirely transparent and enables it for all sites hosted on Flynn.

Closes #1050

### CODE REVIEW

**Comment by josephglanville** [comment]
LGTM

**Comment by codyaray** [comment]
Does this router terminate the HTTP/2 connection and open an HTTP/1.1 connection to the app or does it proxy/passthrough the HTTP/2 connection?

**Comment by titanous** [comment]
The former. Currently we don't send HTTP/2 requests to the backend instances.

**Comment by codyaray** [comment]
Is there any plan or thoughts for proxying HTTP/2? We're looking for a PaaS which we can use in conjunction with gRPC (grpc.io) which requires HTTP/2 all the way to the backend.

**Comment by titanous** [comment]
@codyaray We'll probably implement this by allowing opaque TLS streams to be proxied to backends without modification: #2082

**Comment by codyaray** [comment]
Okay, thanks for letting me know. I subscribed to that issue for updates on support. :)

**Comment by lmars** [comment]
@codyaray if you are happy to run on a non-standard port, you could use a TCP route:

```
$ flynn route add tcp --service my-app-web --port 8443
```

Then any connections to port 8443 will be proxied directly to a backend.

**Pull request merged**
