### PR TITLE
discoverd,flannel: Wait 20 minutes for appropriate host status

### PR DESCRIPTION
**Pull request by lmars**
Some nodes in a cluster may be booted quicker than others, so we may as well wait longer (exiting leaves the cluster inoperable).

### CODE REVIEW

**Comment by josephglanville** [comment]
Is there any reason not to just wait indefinitely here?

**Comment by temujin9** [comment]
:+1: for @josephglanville's comment.

**Comment by lmars** [comment]
@josephglanville @temujin9 updated to wait indefinitely.

**Comment by josephglanville** [comment]
LGTM

**Pull request merged**
