### PR TITLE
appliance: Mariadb performance tweaks

### PR DESCRIPTION
**Pull request by onnimonni**
Hey!

I opened #3291 earlier today because I'm having terrible performance with mariadb while using WordPress and I wanted to start a pull request to see how much we can boost mariadb appliance performance and if we can agree on some basic settings.

It would be excellent to:
* allow users to tweak the appliance config according to their applications
* provide sane and fast default configs

I haven't yet tested these changes since It was more important for me to get the conversation going for me. But I will try these out soon.

**edit:** Typo fixes

### CODE REVIEW

**Comment by titanous** [comment]
@josephglanville is currently working on a generic way of doing this across databases for all available parameters.

**Comment by onnimonni** [comment]
Alright, Can you show me the issue or PR where I can track this?

**Comment by titanous** [comment]
#1740 (though the work isn't solely on Postgres) PR soon.

**Comment by josephglanville** [comment]
@onnimonni PR should be up shortly. I'm working on a solution that uses the state machine that controls the replication the push out configs online to all database members. 

Thanks for pointing out settings you would like defaults updated for, I will do a pass on all of the databases once I am done with the online reconfig to try make the defaults as sane as possible.

**Comment by titanous** [comment]
I'm going to close this as we have other issues and PRs to track what's going on.

**Pull request closed without merging**
