### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by elimisteve**
...CLI includes *a* local browser-based installer...

Signed-off-by: Steve Phillips <steve@tryingtobeawesome.com>

### CODE REVIEW

**Comment by elimisteve** [comment]
@titanous @josephglanville I created this new PR, in which I signed off on the DCO, hopefully properly :-).

**Comment by titanous** [comment]
The commit message still needs the mentioned `docs: ` subsystem prefix. FYI you can amend the commit and force push, and the PR will update.

**Comment by elimisteve** [comment]
@titanous That do it?

**Comment by lmars** [comment]
LGTM

**Comment by lmars** [comment]
Thanks!

**Pull request merged**
