### PR TITLE
installer: cluster management WIP

### PR DESCRIPTION
**Pull request by jvatic**

### CODE REVIEW

**Comment by jvatic** [comment]
@titanous ready for :eyes:

**Comment by jvatic** [comment]
...except too many changes for github

**Comment by lmars** [comment]
@jvatic it may be worth having a `install-clusters-base` branch with the godeps change, then open this PR to merge into that branch?

**Comment by jvatic** [comment]
@lmars yeah, good idea

**Comment by jvatic** [comment]
Reopened as #1471

**Pull request closed without merging**
