### PR TITLE
cli: Don't wait for job events if expected count is 0

### LINKED ISSUE #2901: Deleting an app that has been scaled to 0 times out waiting for scale down.
```
Timed out waiting for job events. Waited 20 seconds.
expected: map[]
actual: map[]
```

### PR DESCRIPTION
**Pull request by josephglanville**
Fixes deleting apps that have been scaled to 0.

Fixes #2901

### CODE REVIEW

**Comment by lmars** [comment]
LGTM (although we should probably be scaling down all formations for the app being deleted, not just the current release).

**Comment by josephglanville** [comment]
That is a good point. We also need to handle deleting releases when we delete apps too.

**Comment by lmars** [comment]
@josephglanville 

> We also need to handle deleting releases when we delete apps too.

True, but we should probably make releases belong to apps first (see https://github.com/flynn/flynn/pull/2769#issuecomment-216002816) to make it easier to know which releases to delete.

Perhaps open another issue / PR rather than blocking this PR?

**Comment by josephglanville** [comment]
Indeed, we can tackle those 2 separately.

**Pull request merged**
