### PR TITLE
dashboard: Show deploy logs in UI + minor fixes

### PR DESCRIPTION
**Pull request by jvatic**
screen shot 2015-01-14 at 3 50 52 pm

Note that only apps deployed through the dashboard with this version or later will have deploy logs visible in the dashboard UI.

### CODE REVIEW

**Comment by titanous** [comment]
I think we should show at least timestamps in the logs list. Is there any other identifying information that would make sense?

**Comment by lmars** [comment]
I don't think the `DOWN` label makes sense, maybe `Finished`?

**Comment by jvatic** [comment]
We can add any identifying information we want to the job meta (such as the git ref). I think timestamps definitely make sense (for both sets of logs).

Yeah, the `DOWN` label is a bit odd in the context of deploy logs.

**Comment by jvatic** [comment]
screen shot 2015-01-15 at 1 37 17 pm

**Comment by jvatic** [comment]
@titanous, @lmars Comments addressed

**Comment by titanous** [comment]
LGTM

**Pull request merged**
