### PR TITLE
Update release + installation workflow to use a TUF repository

### LINKED ISSUE #617: updater: Rolling out new images
First we need to make sure images have associated tarsums, see #612.

Then:

- [ ] Use an S3 backed [tuf](https://github.com/theupdateframework/tuf) repository for version manifests (initial Go implementation [here](https://github.com/flynn/go-tuf))
- [ ] Add the generated image manifest (including tarsums) to the tuf repo (possibly embedded in the [release manifest](https://github.com/flynn/flynn/blob/master/script/release-flynn#L129-L137))
- [ ] Create an `updater` binary which takes a tuf root key, downloads the image manifest and passes it off to `flynn-host download` (or downloads images itself)

Part of #276.

### LINKED ISSUE #864: Installation strategy proposal
With the soon to be merged changes which modify `flynn-host download` to get the image manifest from the TUF repo (#617), the host and bootstrap manifests shipped with the deb package will become stale and should not be used. To fix this, we should not ship manifests directly to users and instead always consult the TUF repo.

I propose removing the OS specific packaging and just downloading and running an installer script (e.g. `curl -sL https://dl.flynn.io/installer.sh | sudo bash`).

The installer script will do the following:

* Install dependencies (e.g. `apt-get install libvirt-bin`)
* Download the latest `flynn-host` binary (e.g. `https://dl.flynn.io/flynn-host`) and verify it using a checksum embedded in the installer script
* Run `flynn-host download` to download the latest images from the TUF repo
* Save the output of `flynn-host download` (which is the manifest of downloaded images) to a local file

The following changes will then be needed:

* `flynn-host daemon` reads the manifest saved by the installer script to determine the IDs of the images it needs to use
* `flynn-host bootstrap` downloads `bootstrap_manifest.json` from the TUF repo before starting

Please add any thoughts as comments to this issue, I plan to start on this soon.

### PR DESCRIPTION
**Pull request by lmars**
These commits have all been reviewed and merged into the `image-updates-base` branch (with the exception of ad3c64f which updates the TUF root keys to production ones).

Once this is merged, I plan to add a daily cron job to the build machine to bump the timestamp of the TUF repo at 6pm UTC in case a nightly build fails.

Closes #617
Closes #864

### CODE REVIEW

**Comment by lmars** [comment]
I also plan to do a full release using this branch before merging so the installation docs are accurate.

**Comment by titanous** [comment]
LGTM (though CI should be green before merging).

Please open an issue about fixing the demo environment Vagrantfile as soon as we have a successful release with the new system. Also, don't forget to disable the release cron while running the manual release.

**Comment by lmars** [comment]
@titanous I had to revert to using `< <(curl ...)`, see c80b988

**Comment by titanous** [comment]
Okay, that's fine, don't forget to squash.

**Comment by titanous** [comment]
Okay, make sure you squash before merging.

**Comment by lmars** [comment]
I did a full release using commit ad3c64f and everything built ok. I have also done a successful install + bootstrap on an EC2 instance using `https://dl.flynn.io/install-flynn`.

I've added a timestamp cronjob to the build machine (daily @ 18:00 UTC), and added the TUF keys to the release cronjob env.

**Comment by titanous** [comment]
I've deployed the website with the updated installation instructions. Nice work! :cocktail:

**Pull request merged**
