### PR TITLE
dashboard: Cluster status page

### LINKED ISSUE #1725: dashboard: Add status view
Add view for new health status service introduced in #1715.

### LINKED ISSUE #2921: Show current flynn version in dashboard
It would be nice if the dashboard displayed the current version of flynn-host, bonus points for displaying a notification if you are not running the latest version.

### PR DESCRIPTION
**Pull request by jvatic**
screen shot 2016-06-15 at 13 56 54
screen shot 2016-06-15 at 13 57 18

Closes #2921
Closes #1725

### CODE REVIEW

**Comment by titanous** [comment]
We should use completely different icons for up/down so that color-blind people can figure out what's going on.

**Comment by jvatic** [comment]
@titanous Yeah, it is a bit difficult to tell them apart at the moment with some of the color blind filters.

**Comment by jvatic** [comment]
Updated icons

**Comment by kwando** [comment]
I would like to see a bigger difference between healthy and unhealthy tiles, maybe different background colors.

**Comment by jvatic** [comment]
Added a red bottom border to unhealthy tiles

**Comment by jvatic** [comment]
Also worth noting here that the status is pulled every ten minutes

**Comment by titanous** [comment]
LGTM

**Pull request merged**
