### PR TITLE
Raise pg `max_connections` to 400

### PR DESCRIPTION
**Pull request by dashkb**
See #2485

### CODE REVIEW

**Comment by titanous** [comment]
Thanks! Please add a prefix of `appliance/postgresql: ` to the commit message as well as a [DCO sign-off](https://flynn.io/docs/contributing#developer%E2%80%99s-certificate-of-origin)

**Comment by dashkb** [comment]
>  as well as a DCO sign-off

Did I do it wrong?

Looks like I broke something... it wasn't immediately obvious what/how from the logs on the CI tool.

**Comment by titanous** [comment]
You didn't do anything wrong, CI is a bit upset right now, I'm working on fixing it.

**Comment by titanous** [comment]
LGTM, thanks!

**Comment by davidhbase** [comment]
If flynn support the pgpoolII? and also how to work with the mutiple postgres masters? If not, how can we realize the postgres scaling funciton?

Thanks

**Pull request merged**
