### PR TITLE
installer: Add workaround for issue #3035

### PR DESCRIPTION
**Pull request by jvatic**

### CODE REVIEW

**Comment by titanous** [comment]
Does this also apply to the `migrate-domain` command? Has it already been fixed in the domain migration worker code?

**Comment by jvatic** [comment]
@titanous I believe it does, however I've yet to track down the source of the issue.

**Comment by jvatic** [comment]
This also fixes #3031

**Comment by titanous** [comment]
I'd like to see the root cause identified and fixed before merging this.

**Comment by titanous** [comment]
Superceded by #3049.

**Pull request closed without merging**
