### PR TITLE
Add CA root certificates to docker-receive

### LINKED ISSUE #3067: Docker-receive failing with 500, "error authorizing context: basic authentication failed"
When I try and deploy any docker image on ```v20160620.1```, I end up with a ```received unexpected HTTP status: 500 Internal Server Error``` after I do ```flynn docker login``` (which receives no output, but no errors, either) and, for instance, ```flynn -a hello-world docker push google/nodejs-hello:latest.``` (After creating ```hello-world```, of course.)

FWIW, this is from a bash script on a Jenkins Docker image running on Docker on a different machine (non-Flynn), but I've verified that my ```~/.flynnrc``` is correct by comparing it across both machines. I can't do it locally, either - I'm running into issues with the CA certs on my OS X local machine which I haven't had time to really debug. (I tried the steps in the prompt to no avail, which is fine, we'll be deploying from this jenkins box, anyway.) 

I've also tried several different things by attaching myself directly to the box and running the same commands. No dice there, either.

Looking at the docker-receive logs, I notice I'm getting:

```2016-07-06T21:37:09.123568Z app[app.ip172315675-1997a1d4-f54f-4484-bafc-00c2e955b86c]: time="2016-07-06T21:37:09Z" level=warning msg="error authorizing context: basic authentication failed" http.request.host="100.100.76.11:80" http.request.id=26e54a31-9633-4a76-a246-ebad40205cf7 http.request.method=GET http.request.remoteaddr="100.100.76.11:47671" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=054ca103-106a-41f0-83ec-1c1b48cbfb53 version=v20160624.1```

Help?

### PR DESCRIPTION
**Pull request by titanous**
Closes #3067

### CODE REVIEW

**Comment by lmars** [comment]
LGTM

**Comment by brettneese** [comment]
Is there a way we can hotfix this into a running cluster? :)

**Comment by titanous** [comment]
@brettneese Yes, I'll get a release running and provide instructions after it's up.

**Comment by brettneese** [comment]
@titanous awesome, you guys rock <3

**Comment by titanous** [comment]
@brettneese This command should update the docker-receive app to include CA certificates (you'll need [`jq`](https://stedolan.github.io/jq/)):

```text
flynn -a docker-receive release show --json | jq 'del(.id) | del(.artifacts) | del(.artifact)' > docker-receive.json && flynn -a docker-receive release add -f docker-receive.json "https://docker.io?name=flynn/docker-receive&id=sha256:19cee7418cda025b6bf25a733fb344b182f24946f6cf24517a46a0f3c5a8dac3"
```

**Pull request merged**
