### PR TITLE
script: Added support for Ubuntu 18.04 in the install script.

### PR DESCRIPTION
**Pull request by philiplb**
Closes https://github.com/flynn/flynn/issues/4392

### CODE REVIEW

**Comment by lmars** [comment]
@philiplb Thanks! Have you tested this on 18.04?

**Comment by philiplb** [comment]
Hi, yes, I launched an EC2 instance with Ubuntu 18.04 and ran a slightly modified version of this script with the FLYNN_HOST_CHECKSUM from the install script from dl.flynn.io It went through successfully. I didn't launch the flynn-host afterwards though.

**Comment by philiplb** [comment]
Thx @AnikHasibul. :-)

**Comment by philiplb** [comment]
Closed due to https://github.com/flynn/flynn/commit/8ac5d71325e4c1efcb6008bf6377995370f7837f

**Pull request closed without merging**
